config/routes.rb
EasySCM::Application.routes.draw do
  resources :test_scenarios

  resources :features

  resources :messages

  resources :test_cases

  root :to => "test_cases#index"

end

app/models/test_case.rb
class TestCase < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/test_cases_controller.rb
class TestCasesController < ApplicationController

  # GET /test_cases
  # GET /test_cases.xml
  def index
    @test_cases = TestCase.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @test_cases }
    end
  end

  # GET /test_cases/1
  # GET /test_cases/1.xml
  def show
    @test_case = TestCase.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @test_case }
    end
  end

  # GET /test_cases/new
  # GET /test_cases/new.xml
  def new
    @test_case = TestCase.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @test_case }
    end
  end

  # GET /test_cases/1/edit
  def edit
    @test_case = TestCase.find(params[:id])
  end

  # POST /test_cases
  # POST /test_cases.xml
  def create
    @test_case = TestCase.new(params[:test_case])

    respond_to do |format|
      if @test_case.save
        format.html { redirect_to(@test_case, :notice => 'Test case was successfully created.') }
        format.xml  { render :xml => @test_case, :status => :created, :location => @test_case }
        format.js
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @test_case.errors, :status => :unprocessable_entity }
        format.js
      end
    end
  end

  # PUT /test_cases/1
  # PUT /test_cases/1.xml
  def update
    @test_case = TestCase.find(params[:id])

    respond_to do |format|
      if @test_case.update_attributes(params[:test_case])
        format.html { redirect_to(@test_case, :notice => 'Test case was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @test_case.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /test_cases/1
  # DELETE /test_cases/1.xml
  def destroy
    @test_case = TestCase.find(params[:id])
    @test_case.destroy

    respond_to do |format|
      format.html { redirect_to(test_cases_url) }
      format.xml  { head :ok }
      format.js   { render :nothing => true }  
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/test_cases_helper.rb
module TestCasesHelper
end

app/views/layouts/application.html.erb
<html>
<head>
  <title>Ajax table manipulation attempt</title>
  <%= stylesheet_link_tag "application" %>
  <%= javascript_include_tag :defaults %>
</head>
<body>

<div id="content">
<%= yield %>
</div>

</body>
</html>

app/views/test_cases/_form.html.erb
<%= form_for(@test_case, :remote => true ) do |f| %>
  <% if @test_case.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@test_case.errors.count, "error") %> prohibited this test_case from being saved:</h2>

      <ul>
      <% @test_case.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/test_cases/create.js.erb
$('body').html("<h1><%= escape_javascript(@test_case.title) %></h1>").append("<%= escape_javascript(@test_case.description) %>").append(<%= link_to 'Back', test_cases_path %>);

app/views/test_cases/edit.html.erb
<h1>Editing Test Case <%= @test_case.name  %></h1>

<%= render 'form' %>

<%= link_to 'Show', @test_case %> | <%= link_to 'Back', test_cases_path %>

app/views/test_cases/index.html.erb
<h1>Listing test_cases</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Title</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @test_cases.each do |test_case| %>
  <tr>
    <td><%= test_case.name %></td>
    <td><%= test_case.title %></td>
    <td><%= test_case.description %></td>
    <td><%= link_to 'Show', test_case %></td>
    <td><%= link_to 'Edit', edit_test_case_path(test_case) %></td>
    <td><%= link_to 'Destroy', test_case, :confirm => 'Are you sure?', :remote => true, :class =>'delete_test_case', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Test case', new_test_case_path %>

app/views/test_cases/new.html.erb
<h1>New Test case</h1>

<%= render 'form' %>

<%= link_to 'Back', test_cases_path %>

app/views/test_cases/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @test_case.name %>
</p>

<p>
  <b>Title:</b>
  <%= @test_case.title %>
</p>

<p>
  <b>Description:</b>
  <%= @test_case.description %>
</p>


<%= link_to 'Edit', edit_test_case_path(@test_case) %> |
<%= link_to 'Back', test_cases_path %>